version: '3.4'

services:
  ittemapi:
    depends_on: 
          - "postgres"

    image: ${DOCKER_REGISTRY-}ittemapi

    build:
      context: .
      dockerfile: IttemAPI/Dockerfile

    ports:
        - "5000:5000" 

    environment:
        ASPNETCORE_URLS: "http://+:5000"

  postgres:
    container_name: 'ITTEM.Database'
    command: postgres -c 'max_connections=500'
    image: postgres:latest
    restart: always

    environment:
        - POSTGRES_USER=iteem
        - POSTGRES_PASSWORD=iteem1234
        - POSTGRES_DB=iteemdb

    volumes:
        - ../volumes/postgres_data:/var/lib/postgresql/data

    ports:
        - "5431:5432"

    networks:
        - iteem-network

networks:
  iteem-network:
    driver: bridge
